### ISSUE TITLE
Error: Call requires API level 26 (current min is 21): setAttributeFromXml [NewApi]

### ISSUE THREAD

**Issue by mutairibassam** [qamarelsafadi/CurvedBottomNavigation#1]
@qamarelsafadi After doing a health check in the code, I found one of the used APIs requires minimum level 26 without putting any condition. So, I did a test in API 24 and caused a run time error.

Before applying any fixes, can you please let me know if you did any test for APIs less than 26?

Code:
https://github.com/qamarelsafadi/CurvedBottomNavigation/blob/fc119e80ab54e29ef005032616e2bd442249154c/curvedBottomNaviagtion/src/main/java/com/qamar/curvedbottomnaviagtion/CurvedBottomNavigation.kt#L136

https://github.com/qamarelsafadi/CurvedBottomNavigation/blob/fc119e80ab54e29ef005032616e2bd442249154c/curvedBottomNaviagtion/src/main/java/com/qamar/curvedbottomnaviagtion/CurvedBottomNavigation.kt#L145

**Comment by qamarelsafadi** [comment]
Hey Bassam, 
Glad to see your contribution, and yup, unfortunately,
I didn't do any test for APIs less than 26, 
I will check your pull request and merge it as soon as possible, 
I am still waiting for your Compose contribution,

Have a good day,
