### ISSUE TITLE
[Feature] Color selection based on user input

### ISSUE THREAD

**Issue by mutairibassam** [qamarelsafadi/CurvedBottomNavigation#3]
Noticed colors are fixed and not based on user input which limits developers to follow their application theme. I recommend to allow developers to specify the colors.

**Comment by qamarelsafadi** [comment]
Colors are not fixed,
You can pass them from your colors.xml file 
or pass the hex code as the following : 

```xml 
   <com.qamar.curvedbottomnaviagtion.CurvedBottomNavigation
        android:id="@+id/bottomNavigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:cbn_background="#888787"
        app:cbn_fabColor="#FF0A0A"
        app:cbn_iconColor="#FF0A0A"
        app:cbn_height="76dp"
        app:cbn_icon_size="14dp"
        app:cbn_selected_icon_size="48dp"
        app:cbn_selectedIconColor="@color/purple_200"
        app:cbn_titleColor="@color/purple_500"/>
```

**Comment by mutairibassam** [comment]
@qamarelsafadi Sorry, I am trying to educate myself to the code. Can you explain the use of hardcoded color values?

For example:
https://github.com/qamarelsafadi/CurvedBottomNavigation/blob/443ffa6a893b840ae50b26c90a7c1052b7cfe55c/curvedBottomNaviagtion/src/main/java/com/qamar/curvedbottomnaviagtion/CurvedBottomNavigation.kt#L41

**Comment by qamarelsafadi** [comment]
@mutairibassam Yup no problem dear,
Its just for default value.
